version: '3.9'
services:
  common:
#    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: safekids-ai/ml-models:1

  api:
    image: safekids-ai/ml-models:1
    command: ["node", "dist/ml-api/main.js"]
    ports:
      - 3000:3000
    depends_on:
      - common
  web:
    image: safekids-ai/ml-models:1
    environment:
      API_URL: "http://api:3000"
      PORT: 4200
      PORT_PREVIEW: 4300
      #DEBUG: "vite:*"
    command: ["npx", "http-server", "/apps/dist/ml-api-web/", "-p 4200", "-d false", "-g true", "-b true", ""]
    ports:
      - 3001:4200
    depends_on:
      - api
