version: '3.9'
services:
  common:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: safekids-ai/ml-models:1

  api:
    image: safekids-ai/ml-models:1
    command: ["npx", "nx", "serve", "ml-api", "--configuration=development"]
    ports:
      - 3000:3000
    depends_on:
      - common
  web:
    image: safekids-ai/ml-models:1
    environment:
      API_URL: "http://api:3000"
      PORT: 4200
      PORT_PREVIEW: 4300
      #DEBUG: "vite:*"
    command: ["npx", "nx", "serve", "ml-api-web", "--configuration=development"]
    ports:
      - 3001:4200
      - 3002:4300
    depends_on:
      - api
